Updated spec, schema based on goodtables.next
frictionlessdata/data-quality-spec pull request #6
Opened 2016-10-31 18:24 UTC by roll

- fixes #3

---

Here is a question - should be `weight` hard-coded to spec or it's more application/user level thing (cc @pwalsh @amercader)

2016-10-31 18:51 UTC, pwalsh commented
@roll yes, hard code it. We don't use it in GT anyway right now.

2016-10-31 18:53 UTC, pwalsh commented
@roll you've completely dropped name and message. Why?

2016-11-01 07:16 UTC, pwalsh requested changes
This needs discussion and changes before merging.

2016-11-01 07:16 UTC, pwalsh commented on spec.json
> +    "errors": [
having errors as an array makes just that bit harder to detect duplicate error codes. Seeing as error codes **need** to be unique, why not have an object where the keys are the codes?

2016-11-01 07:16 UTC, pwalsh commented on spec.json
> +          "type": "general",
`general` as a type means little. Why is it better than the current `format`, which at least indicates "it is not the format we expect it is"?

2016-11-01 07:16 UTC, pwalsh commented on spec.json
> +          "context": "any",
I am confused by `context`. When I read all the different values for context, I don't really understand what they mean. If anything, they feel like they may be very specific to your implementation of good tables, but perhaps not relevant/useful in a generic data quality spec.

Also, it means there are now two taxonomies: `type` and `context`.

What problem does `context` solve?

2016-11-01 07:16 UTC, pwalsh commented on spec.json
> +        {
We are missing two things here that to me seem so critical, I'm not sure why they are not here:

1. `name`: we need a human readable name. GoodTables errors are collated into human-targeted reports. These currently manifest in the GoodTables web UI, and some client libs like in OpenSpending and DataPackagist. Why have you removed name?
2. `message`: like name, we need really clear human readable messages, that can be used by non-technical people to fix errors in their tabular data. Again, the GoodTables UI has many examples of this. In the original spec here, I presented a message string for each error than can easily be manipulated in any programming language that might implement this spec. Why remove it?

2016-11-01 07:16 UTC, pwalsh commented on spec.json
> +        {
Also as mentioned in the general comments, we also need to add back weight

2016-11-01 09:46 UTC, roll commented
@pwalsh 
Thanks.

### name

my bad. will add

### weight

OK. But I have question - why numbers like 9, 6 etc Not 5, 10 etc Just curious)

### general vs format

I was just trying to find other word then `format` because there is already `format-error` (just one of the type). Also errors like `http-error` don't fit very well with `format` and here could be added other general error we don't know for now. But it's your call. I'm OK with any.

### array vs dict

Dict is better for users but GT requires ordered data structure. Let's handle order on GT level having dict in spec. Anyway using spec indirectly could be a problem. So it could be better to have some middleware structure on `Inspector` level (to provide order e.g.).

### context

Yes, it's vital for GT but it could be managed on GT level. Other question that in my opinion it's more than just implementation detail. Context (WHERE error is) seems pretty natural to describe tabular data:

![dataset](https://cloud.githubusercontent.com/assets/557395/19885340/1fcd55d8-a02f-11e6-8228-eea890e491d5.png)

But it's ok to remove from spec.

### message and description

This one is the most questionable for me. Hard-coding message templates will couple spec and implementations too much in my opinion. E.g. I've added many new data to messages for GT.next like `duplicate-row`'s additionally row numbers with the same values etc I see it as an active ongoing process (improving this messages) further. And if we're going to make all changes thru spec it could slow down this improvements. I suppose better to have something like recommended message or just a good description and let implementation handle concrete messages. WDYT?

2016-11-02 09:02 UTC, pwalsh commented
@roll is good tables now using these messages? Apart from that, all looks good.

2016-11-02 09:04 UTC, roll commented
@pwalsh 
I'll next make a separate PR to update GT to work with this spec (and will use this messages as templates). So it's the last thing.

2016-11-02 09:05 UTC, pwalsh approved these changes
can merge

2016-11-02 09:12 UTC, merged